### 1. Data Understanding


In [1]:
# Importing Necessary Libiaries
#  လိုအပ်တဲ့ Library တွေကို သွင်းမယ်
import pandas as pd
import numpy as np

In [2]:
# Read Data
# Data တွေကို ဖတ်မယ်
train_data = pd.read_csv('/content/sample_data/california_housing_train.csv')
test_data = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
train_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
train_data.shape

(17000, 9)

In [ ]:
train_data.shape[0]

17000

In [ ]:
train_data.shape[1]

9

In [ ]:
test_data.shape

(3000, 9)

In [ ]:
train_data.iloc[0] # index based location

longitude              -114.3100
latitude                 34.1900
housing_median_age       15.0000
total_rooms            5612.0000
total_bedrooms         1283.0000
population             1015.0000
households              472.0000
median_income             1.4936
median_house_value    66900.0000
Name: 0, dtype: float64

In [ ]:
train_data.iloc[1]

longitude              -114.47
latitude                 34.40
housing_median_age       19.00
total_rooms            7650.00
total_bedrooms         1901.00
population             1129.00
households              463.00
median_income             1.82
median_house_value    80100.00
Name: 1, dtype: float64

In [ ]:
train_data.iloc[16999]

longitude              -124.3500
latitude                 40.5400
housing_median_age       52.0000
total_rooms            1820.0000
total_bedrooms          300.0000
population              806.0000
households              270.0000
median_income             3.0147
median_house_value    94600.0000
Name: 16999, dtype: float64

In [ ]:
train_data.iloc[:]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
train_data.iloc[:,0:-1]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

In [ ]:
train_data.iloc[:,-1]

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
# data ကို ထုတ်ကြည့်တာ။
train_data
test_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
print(train_data.shape)
print(test_data.shape)

(17000, 9)
(3000, 9)


In [ ]:
train_data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

### 2. Data Preprocessing

In [ ]:
# null values တွေကို ဖယ်တဲ့ Code

#Note: By default, the dropna() method returns a new DataFrame, and will not change the original.
# If you want to change the original DataFrame, use the inplace = True argument:

train_data.dropna(inplace = True)
test_data.dropna(inplace= True)


In [ ]:
train_data.iloc[:,-1]
# train_data.iloc[:, 0:-1 ]

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
# features X နဲ့  Labels Y ခွဲပေးတဲ့ Code,
# in short, feautures == x and labels == y
# features = input value that describes the characteristics of such labels in datasets
# label = output value

X_train = train_data.iloc[:,:-1].values
Y_train = train_data.iloc[:,-1].values

X_test = test_data.iloc[:,:-1].values
Y_test = test_data.iloc[:,-1].values



In [ ]:
print(len(X_train))

17000


In [ ]:
train_data.iloc[: 2, :]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0

In [ ]:
train_data.iloc[: 2, :].values


array([[-1.1431e+02,  3.4190e+01,  1.5000e+01,  5.6120e+03,  1.2830e+03,
         1.0150e+03,  4.7200e+02,  1.4936e+00,  6.6900e+04],
       [-1.1447e+02,  3.4400e+01,  1.9000e+01,  7.6500e+03,  1.9010e+03,
         1.1290e+03,  4.6300e+02,  1.8200e+00,  8.0100e+04]])

In [ ]:
print("Features of Training Data", X_train)
print("Labels of Training Data", Y_train)

Features of Training Data [[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]
Labels of Training Data [ 66900.  80100.  85700. ... 103600.  85800.  94600.]


In [ ]:
print("Features of row 1", X_train[0])
print("Labels of row 1", Y_train[0])

Features of row 1 [-1.1431e+02  3.4190e+01  1.5000e+01  5.6120e+03  1.2830e+03  1.0150e+03
  4.7200e+02  1.4936e+00]
Labels of row 1 66900.0


### 3. Modeling

In [ ]:
import sklearn
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# fitting the data
model.fit(X_train, Y_train)    #model.fit က for modelling
# Training Data


LinearRegression()

In [ ]:
#  Testing Data ရဲ့Features တွေပေးပြီး ခန့်မှန်းမယ်။
# predict the data
Y_predicted = model.predict(X_test)   #to test, give only features

In [ ]:
print(Y_predicted[0: 3])

[352812.31112455 212717.70074518 272344.6995189 ]


In [ ]:
# မူလ ရှိတဲ့ Labels ကို ကြည့်ကြမယ်။
print(Y_test[0:3])

[344700. 176500. 270500.]


In [ ]:
len(Y_test)

3000

### 4. Evaluation

In [ ]:
# Mean Abs Error
total = 0
for i in range(len(Y_test)):
  abs_error = abs(Y_test[i]-Y_predicted[i])
  total += abs_error
mae = total/len(Y_test)
print("Mean Abs Error", mae)

Mean Abs Error 50352.22825794292


In [ ]:
# Mean Square Error
total = 0
for i in range(len(Y_test)):
  abs_error = (Y_test[i]-Y_predicted[i])**2
  total += abs_error
mse = total/len(Y_test)
print("Mean square Error", mse)

Mean square Error 4867205486.928794
